# -*- coding: utf-8 -*-
"""AlphaDay2_DataSurgeon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTuRqcHTsap-C1VGJxlJhD5N2aVsyU1L

Setup Python Environment
"""

pip install pandas

import pandas as pd

"""Load Data"""

df = pd.read_csv('broken_sales_data.csv')

print(df)

"""Checking Missing Values"""

print(df.isnull().sum())

"""Replacing Nulls"""

median_sales = df[df["Category"] == "Electronics"]["Sales"].median()

df["Sales"] = df["Sales"].fillna(median_sales)

df.loc[df["Product"] == "Chair" , "Quantity"] = 1

"""Detecting Outlier"""

outlier = df[df["Quantity"] > 100]
print(outlier)

"""Removing Outlier"""

mean_quantity = df[df["Category"] == "Office"]["Quantity"].mean()
df.loc[df["Quantity"] > 100] = mean_quantity

print(df.info())

"""Cleaned Data"""

print(df)

import pandas as pd
import plotly.express as px

# Group by Category
summary = df.groupby("Category")["Sales"].sum().reset_index()

fig = px.bar(
    summary,
    x="Category",
    y="Sales",
    title="Total Sales by Category (Cleaned Data)",
)

# Show plot
fig.show()

